CREATE DATABASE TRABALHO;

USE TRABALHO;

CREATE TABLE TAREFA(
	IDTAREFA INT PRIMARY KEY AUTO_INCREMENT,
	NOME_TAREFA VARCHAR(25) NOT NULL,
	DESCRICAO_TAREFA VARCHAR(50) NOT NULL
);

CREATE TABLE PROFESSOR(
	IDPROFESSOR INT PRIMARY KEY AUTO_INCREMENT,
	NOME_PROFESSOR VARCHAR(50) NOT NULL,
	SENHA_PROFESSOR VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE TAREFA_PROFESSOR(
    ID_TAREFA INT,
    ID_PROFESSOR INT,
    CONSTRAINT TAREFA_PROFESSOR_PK PRIMARY KEY (ID_TAREFA, ID_PROFESSOR),
    CONSTRAINT TAREFA_PROFESSO_TAREFA_FK FOREIGN KEY(ID_TAREFA) REFERENCES TAREFA(IDTAREFA),
    CONSTRAINT TAREFA_PROFESSO_PROFESSOR_FK FOREIGN KEY(ID_PROFESSOR) REFERENCES PROFESSOR(IDPROFESSOR)
);

INSERT INTO TAREFA VALUES(NULL,"PROVA01", "FAZER EXERCICIOS PROPOSTOS");
INSERT INTO TAREFA VALUES(NULL,"PROVA01 RECUPERACAO", "FAZER EXERCICIOS PROPOSTOS");
INSERT INTO TAREFA VALUES(NULL,"PROVA02", "FAZER EXERCICIOS PROPOSTOS");
INSERT INTO TAREFA VALUES(NULL,"PROVA02 RECUPERACAO", "FAZER EXERCICIOS PROPOSTOS");

INSERT INTO PROFESSOR VALUES(NULL,"JOAQUIM", "123456");
INSERT INTO PROFESSOR VALUES(NULL,"PEDRO", "159753");
INSERT INTO PROFESSOR VALUES(NULL,"PEDRO", "357951");

INSERT INTO TAREFA_PROFESSOR VALUES(1,3);
INSERT INTO TAREFA_PROFESSOR VALUES(4,1);
INSERT INTO TAREFA_PROFESSOR VALUES(2,2);
INSERT INTO TAREFA_PROFESSOR VALUES(3,1);

SELECT NOME_PROFESSOR AS "PROFESSOR", NOME_TAREFA AS 'TAREFA', DESCRICAO_TAREFA AS "DESCRIÇÃO"
FROM TAREFA_PROFESSOR
INNER JOIN TAREFA
ON IDTAREFA = ID_TAREFA
INNER JOIN PROFESSOR
ON IDPROFESSOR = ID_PROFESSOR;
